//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doof.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("doof.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Adds &lt;/br&gt;No Annoying Popups &lt;/br&gt;Simply &lt;span class=&quot;text-decoration-underline&quot;&gt;Recipes&lt;/span&gt;.
        /// </summary>
        internal static string hero {
            get {
                return ResourceManager.GetString("hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here.
        /// </summary>
        internal static string hero_button {
            get {
                return ResourceManager.GetString("hero-button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All recipes.
        /// </summary>
        internal static string hero_text {
            get {
                return ResourceManager.GetString("hero-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Terry for recipe messurements while cooking, leave your phone on the counter..
        /// </summary>
        internal static string terry_1 {
            get {
                return ResourceManager.GetString("terry-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need general cooking advise while cooking? Terry is not tied to only the recipe..
        /// </summary>
        internal static string terry_2 {
            get {
                return ResourceManager.GetString("terry-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let Terry guide you through every step of the cooking process..
        /// </summary>
        internal static string terry_3 {
            get {
                return ResourceManager.GetString("terry-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can Terry do for you?.
        /// </summary>
        internal static string terry_subtitle {
            get {
                return ResourceManager.GetString("terry-subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Terry, your cooking partner.
        /// </summary>
        internal static string terry_title {
            get {
                return ResourceManager.GetString("terry-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast website with just the information you need..
        /// </summary>
        internal static string why_1 {
            get {
                return ResourceManager.GetString("why-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized for different languages..
        /// </summary>
        internal static string why_2 {
            get {
                return ResourceManager.GetString("why-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build in voice cooking assistant to help you while cooking.
        /// </summary>
        internal static string why_3 {
            get {
                return ResourceManager.GetString("why-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why choose doof?.
        /// </summary>
        internal static string why_title {
            get {
                return ResourceManager.GetString("why-title", resourceCulture);
            }
        }
    }
}
