//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doof.Resources.Pages.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterConfirmation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterConfirmation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("doof.Resources.Pages.Account.RegisterConfirmation", typeof(RegisterConfirmation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email to confirm it..
        /// </summary>
        internal static string check_email {
            get {
                return ResourceManager.GetString("check-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app does not currently have a real email sender registered, see &lt;a href=&quot;https://aka.ms/aspaccountconf&quot;&gt;these docs&lt;/a&gt; for how to configure a real email sender.
        ///        Normally this would be emailed: .
        /// </summary>
        internal static string confirm_email {
            get {
                return ResourceManager.GetString("confirm-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to confirm.
        /// </summary>
        internal static string confirm_link {
            get {
                return ResourceManager.GetString("confirm-link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page where it shows that you should confirm your email..
        /// </summary>
        internal static string meta_desc {
            get {
                return ResourceManager.GetString("meta-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm, email, doof, recipes.
        /// </summary>
        internal static string meta_keywords {
            get {
                return ResourceManager.GetString("meta-keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
