//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doof.Resources.Pages.Account.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChangePasswordModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangePasswordModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("doof.Resources.Pages.Account.Manage.ChangePasswordModel", typeof(ChangePasswordModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length have to be from 6 to 100 characters..
        /// </summary>
        internal static string new_password_length {
            get {
                return ResourceManager.GetString("new-password-length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required..
        /// </summary>
        internal static string new_password_required {
            get {
                return ResourceManager.GetString("new-password-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is required..
        /// </summary>
        internal static string old_password_required {
            get {
                return ResourceManager.GetString("old-password-required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was successfully changed..
        /// </summary>
        internal static string password_change_success {
            get {
                return ResourceManager.GetString("password-change-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both new passwords have to match..
        /// </summary>
        internal static string password_compare {
            get {
                return ResourceManager.GetString("password-compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password have to be in valid format..
        /// </summary>
        internal static string password_valid {
            get {
                return ResourceManager.GetString("password-valid", resourceCulture);
            }
        }
    }
}
