//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doof.Resources.Pages.Account.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("doof.Resources.Pages.Account.Manage.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        internal static string change_email_btn {
            get {
                return ResourceManager.GetString("change-email-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is verified.
        /// </summary>
        internal static string email_confirmed {
            get {
                return ResourceManager.GetString("email-confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email.
        /// </summary>
        internal static string email_placeholder {
            get {
                return ResourceManager.GetString("email-placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page where the user can change their email and see if it is verified or not..
        /// </summary>
        internal static string meta_desc {
            get {
                return ResourceManager.GetString("meta-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change, doof, recipes, email.
        /// </summary>
        internal static string meta_keywords {
            get {
                return ResourceManager.GetString("meta-keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email.
        /// </summary>
        internal static string new_email {
            get {
                return ResourceManager.GetString("new-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string verify_btn {
            get {
                return ResourceManager.GetString("verify-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify this email.
        /// </summary>
        internal static string verify_placeholder {
            get {
                return ResourceManager.GetString("verify-placeholder", resourceCulture);
            }
        }
    }
}
