version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: adrianbodin/doof:latest
    environment:
      SQL_SERVER_CONNECTION: ${SQL_SERVER_CONNECTION}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
    ports:
       - "8000:80"