version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SQL_SERVER_CONNECTION: ${SQL_SERVER_CONNECTION}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    container_name: mssqlserverdoof
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SQL_SERVER_DATABASE_PASSWORD: ${SQL_SERVER_DATABASE_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1443:1443"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    volumes:
      - mssqldb:/var/opt/mssql/data

volumes:
  mssqldb: